version: '3'
services:
  patr2:
    image: "alexburlacu/rtp-server:lab2"
    container_name: patr2
    ports:
      - "4000:4000"
  web:
    build: .
    ports:
      - "5000:5000"
    command: bash -c "sleep 10 && flask run"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - patr2
  redis:
    container_name: cache
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379
    environment:
      - REDIS_URL=redis://cache
  